### ISSUE TITLE
Running test in "Your First Application" shown in Kit docs

### ISSUE THREAD

**Issue by fduhia** [kit-clj/kit-examples#1]
When running the test command `clj -M:test` in the guestbook example, I get the following error:
```
Exception in thread "main" Syntax error macroexpanding at (user.clj:1:1).
...
Cased by: java.io.FileNotFoundException: Could not locate lambdaisland/classpath/watch_deps__init.class...
...
```

To solve this, I added `com.lambdaisland/classpath {:mvn/version "0.0.27"}` to `:test` alias in deps.edn.
I'm not entirely sure why this happens but thought I'd point it out for others going through the docs.

**Comment by yogthos** [comment]
Thanks for the heads up, the problem is caused by `user.clj` requiring classpath for hot loading, and looks like it gets loaded when tests run requiring the dependency there as well.

**Comment by fduhia** [comment]
Happy to help and I appreciate insight into the dependency issue. Thanks for the work you and others are doing on Kit, Cheers.
